Repository DINHDUCCHUNG/ecommerce-be, pull requests merged in 2021-12, with the labels that each got.

#97 feat: add thumbnail to collection
  src/docs/collection.yml
  src/entities/collection.ts
  src/entities/media.ts
  src/migrations/1640340451937-addThumbnailForCollection.ts
  src/migrations/1640342177531-addForeignKeyForMediaInCollection.ts
  src/modules/collection/controllers.ts
  src/modules/collection/daos.ts
  src/modules/collection/services.ts
Labels: feature

#98 Revert "feat: add thumbnail to collection"
  src/docs/collection.yml
  src/entities/collection.ts
  src/entities/media.ts
  src/migrations/1640340451937-addThumbnailForCollection.ts
  src/migrations/1640342177531-addForeignKeyForMediaInCollection.ts
  src/modules/collection/controllers.ts
  src/modules/collection/daos.ts
  src/modules/collection/services.ts
Labels: feature

#100 fix: add thumbnail relation
  src/entities/collection.ts
  src/entities/media.ts
  src/modules/collection/controllers.ts
  src/modules/collection/daos.ts
Labels: bug

#105 fix: foreign key for collection
  src/migrations/1640367300502-addThumbnailForCollection.ts
  src/modules/collection/daos.ts
Labels: bug

#133 fix spell cart return public title
  src/modules/cart/services.ts
  src/modules/order/services.ts
Labels: clean

#134 format return update delete cart
  src/modules/cart/controllers.ts
  src/modules/cart/services.ts
  src/modules/cartItem/controllers.ts
  src/modules/cartItem/daos.ts
  src/modules/cartItem/services.ts
Labels: documentation, support, clean

#135 add more infor shopinfor
  src/docs/shopInfor.yml
  src/entities/shopInfor.ts
  src/migrations/1640774366022-addInfoinShopInfo.ts
  src/modules/shopInfor/controllers.ts
Labels: documentation, support, clean
