Repository DINHDUCCHUNG/ecommerce-be, pull requests merged in 2022-01, with the labels that each got.

#139 add feature update order, add search
  src/constants/orderStatus.ts
  src/docs/order.yml
  src/modules/order/controllers.ts
  src/modules/order/daos.ts
  src/modules/order/services.ts
  src/routes/order.ts
Labels: feature, delay

#147 fix bug order api
  src/docs/order.yml
  src/entities/order.ts
  src/migrations/1641221741056-dropDetailAdress.ts
  src/modules/cart/controllers.ts
  src/modules/order/controllers.ts
  src/modules/order/daos.ts
  src/modules/order/services.ts
  src/routes/order.ts
Labels: bug

#150 fix update cart after checkout
  src/modules/cartItem/daos.ts
  src/modules/cartItem/services.ts
  src/modules/order/controllers.ts
  src/modules/order/daos.ts
  src/modules/order/services.ts
Labels: bug

#151 addOrderCode
  src/entities/order.ts
  src/migrations/1641293064406-addOrderCode.ts
  src/modules/order/controllers.ts
  src/modules/order/daos.ts
Labels: feature

#154 feat: add total collection
  src/modules/collection/daos.ts
  src/modules/collection/services.ts
  src/modules/vendor/services.ts
Labels: feature

#156 fix: convert any type in file seed
  src/modules/collection/services.ts
  src/seeds/product.ts
Labels: bug

#157 fix: total collection
  src/modules/collection/controllers.ts
Labels: bug

#160 fix check availabel
  src/docs/cart.yml
  src/modules/cart/controllers.ts
  src/modules/cart/services.ts
  src/modules/order/daos.ts
  src/modules/variant/daos.ts
  src/modules/variant/services.ts
  src/routes/cart.ts
Labels: bug

#163 Fix/fix bug
  src/modules/cart/controllers.ts
  src/modules/cart/daos.ts
  src/modules/cart/services.ts
  src/modules/cartItem/controllers.ts
  src/modules/cartItem/daos.ts
  src/modules/cartItem/services.ts
  src/modules/order/controllers.ts
  src/modules/order/daos.ts
  src/utils/sendEmail.ts
Labels: bug, clean

#165 add sort oder by status ,clean code
  src/docs/order.yml
  src/entities/orderItem.ts
  src/modules/article/controllers.ts
  src/modules/cart/controllers.ts
  src/modules/cart/services.ts
  src/modules/collection/controllers.ts
  src/modules/contact/controllers.ts
  src/modules/order/controllers.ts
  src/modules/order/daos.ts
  src/modules/order/services.ts
  src/modules/orderItem/daos.ts
  src/modules/product/daos.ts
  src/modules/shopInfor/controllers.ts
  src/modules/shopInfor/daos.ts
Labels: feature, clean
